{{config(
    materialized='table'
)}}

WITH DATE_SPINE AS (
    SELECT 
        CAST(DATEADD(DAY, SEQ4(), '2025-01-01') AS DATE) AS DATE_DAY
    FROM TABLE(GENERATOR(ROWCOUNT => 10000)) -- Generate 10,000 rows to cover ~27 years
)

SELECT 
    CAST(TO_CHAR(date_day, 'YYYYMMDD') AS NUMBER(8,0)) AS DATE_KEY,
    DATE_DAY AS DATE_FULL,
    YEAR(DATE_DAY) AS DATE_YEAR,
    MONTH(DATE_DAY) AS DATE_MONTH,
    DAY(DATE_DAY) AS DATE_DAY,
    CASE 
        WHEN DAYOFWEEK(DATE_DAY) IN(0, 6) THEN 1 
        ELSE 0 
    END AS IS_WEEKEND, 
    QUARTER(DATE_DAY) AS DATE_QUARTER,
    DAYOFWEEK(DATE_DAY) AS DATE_DAY_OF_WEEK
FROM DATE_SPINE