version: 2 

models:
  - name: dim_location_cleansed 
    description: "Conformed dimensions for Polish job locations."
    columns: 
      - name: location_key 
        tests:
          - not_null
          - unique
  - name: fct_job_postings_cleansed 
    description: "Fact table containing cleansed job postings data."
    columns: 
      - name: job_posting_key
        tests:
          - not_null
          - unique
      - name: location_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_location_cleansed')
              field: location_key
              