{{config(
    materialized='table'
)}}

WITH STG_DATA AS (
    SELECT * FROM {{ ref('stg_adzuna_jobs') }}
), CLEANSED_DATA AS (
SELECT 
    CAST(JOB_ID AS NUMBER(10,0)) AS JOB_ID, 
    CAST(TRIM(JOB_TITLE) AS VARCHAR(255)) AS JOB_TITLE, 
    CAST(TRIM(JOB_DESCRIPTION) AS VARCHAR(500)) AS JOB_DESCRIPTION, 
    CAST(TRIM(COMPANY_NAME) AS VARCHAR(128)) AS COMPANY_NAME,
    CAST(INITCAP(TRIM(VOIVODESHIP)) AS VARCHAR(64)) AS VOIVODESHIP, 
    CAST(INITCAP(TRIM(CITY)) AS VARCHAR(64)) AS CITY,
    CAST(SALARY_MIN AS NUMBER(12,2)) AS SALARY_MIN,
    CAST(SALARY_MAX AS NUMBER(12,2)) AS SALARY_MAX,
    CAST(TRIM(JOB_URL) AS VARCHAR(550)) AS JOB_URL,
    CAST(TRIM(CATEGORY_LABEL) AS VARCHAR(128)) AS CATEGORY_LABEL,
    CAST(UPPER(TRIM(CATEGORY_TAG)) AS VARCHAR(128)) AS CATEGORY_TAG,
    CAST(CREATED_AT AS TIMESTAMP_NTZ) AS CREATED_AT,
    CAST(LOADED_AT AS TIMESTAMP_NTZ) AS LOADED_AT
FROM STG_DATA
QUALIFY ROW_NUMBER() OVER (PARTITION BY job_id ORDER BY loaded_at DESC) = 1
)
SELECT * FROM CLEANSED_DATA